apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cassandra
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: cassandra
        visualize: "true"
    spec:
      containers:
        - command:
            - /run.sh
          resources:
            requests:
              memory: 250Mi
              cpu: 250m
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: MAX_HEAP_SIZE
              value: 512M
            - name: HEAP_NEWSIZE
              value: 256M
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: gcr.io/google-samples/cassandra:v8
          name: cassandra
          ports:
            - containerPort: 9042
              name: cql
            - containerPort: 9160
              name: thrift
          volumeMounts:
            - mountPath: /cassandra_data
              name: data
          readinessProbe:
            exec:
              command: nodetool status
            initialDelaySeconds: 10
            timeoutSeconds: 1
      volumes:
        - name: data
          emptyDir: {}
