apiVersion: v1
kind: ReplicationController
metadata:
  name: jenkins
  labels:
    name: jenkins
    visualize: "true"
spec:
  replicas: 1
  selector:
    name: jenkins
  template:
    metadata:
      labels:
        visualize: "true"
        name: jenkins
    spec:
      containers:
      - resources:
          limits:
            cpu: 0.2
        name: jenkins
        image: jenkins:2.0
        ports:
        - containerPort: 8080
          name: main
        - containerPort: 50000
          name: hooks
