apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  template:
    metadata:
      labels:
        visualize: "true"
        name: jenkins
    spec:
      hostNetwork: true
      nodeSelector:
        name: worker-2
      containers:
      - name: jenkins
        image: jenkins:2.3-alpine
        volumeMounts:
          - mountPath: /var/jenkins_home
            name: jenkinsdata
        ports:
          - name: ui
            containerPort: 8080
          - name: hooks
            containerPort: 50000
      volumes:
        - name: jenkinsdata
          hostPath:
            path: /root/volumes/jenkinsdata
