apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pokerui
spec:
  replicas: 1
  template:
    metadata:
      labels:
        visualize: "true"
        name: pokerui
        version: 0.1.1
    spec:
      containers:
      - resources:
          requests:
            cpu: 250m
            memory: 250Mi
          limits:
            cpu: 250m
            memory: 500Mi
        env:
        - name: POKERTRACKER_COMMAND_URL
          value: http://5.189.173.45:30080/pokertracker/
        - name: POKERTRACKER_QUERY_URL
          value: http://5.189.173.45:30083/pokertracker-query/
        name: pokerui
        image: robertbrem/pokerui-docker:0.1.1
        ports:
        - containerPort: 3000
