apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pokertracker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        visualize: "true"
        name: pokertracker
        version: 0.0.13
    spec:
      containers:
      - resources:
          requests:
            cpu: 250m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 750Mi
        env:
        - name: CASSANDRA_IP
          value: cassandra
        name: pokertracker
        image: robertbrem/pokertracker-docker:0.0.13
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /pokertracker/resources/players
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 10
