apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pokertracker-query
spec:
  replicas: 1
  template:
    metadata:
      labels:
        visualize: "true"
        name: pokertracker-query
        version: 0.0.1
    spec:
      containers:
      - env:
        - name: KAFKA_ADDRESS
          value: kafka:9092
        name: pokertracker
        image: robertbrem/pokertracker-query-docker:0.0.1
        ports:
        - containerPort: 8080
