apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
    visualize: "true"
  name: cassandra
spec:
  ports:
  - port: 9042
    name: cql
  - port: 9160
    name: thrift
  selector:
    app: cassandra
