apiVersion: v1
kind: Service
metadata:
  name: devoxx-adesso
  labels:
    name: devoxx-adesso
    visualize: "true"
spec:
  ports:
  - port: 4201
    targetPort: 4200
    nodePort: 30042
  selector:
    name: devoxx-adesso
  type: NodePort
