apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    name: jenkins
    visualize: "true"
spec:
  ports:
  - name: main
    port: 8282
    targetPort: 8080
    nodePort: 30180
  - name: hook
    port: 50000
    targetPort: 50000
    nodePort: 30150
  selector:
    name: jenkins
  type: NodePort
