apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    name: keycloak
    visualize: "true"
spec:
  ports:
  - name: http
    port: 8383
    targetPort: 8080
    nodePort: 30081
  - name: https
    port: 8443
    targetPort: 8443
    nodePort: 30082
  selector:
    name: keycloak
  type: NodePort
