apiVersion: v1
kind: Service
metadata:
  name: pokerui
  labels:
    name: pokerui
    visualize: "true"
spec:
  ports:
  - port: 3001
    targetPort: 3000
    nodePort: 30030
  selector:
    name: pokerui
  type: NodePort
