apiVersion: v1
kind: Service
metadata:
  name: pokertracker-query
  labels:
    name: pokertracker-query
    visualize: "true"
spec:
  ports:
  - port: 8383
    targetPort: 8080
    nodePort: 30083
  selector:
    name: pokertracker-query
  type: NodePort
